#应用名称 
spring:
  application:
    name: dubbo-registry-zookeeper-provider-sample

dubbo:
  application:
    id: auth-branch
    name: auth-branch
  registry: 
    address: zookeeper://127.0.0.1:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status : server
  scan: 
   base-packages: com.davin.dubbo.provider.service.impl
  
